config/routes.rb
Rails.application.routes.draw do
  root to: "inss_calculators#new"

  resource :inss_calculator, only: [ :new, :show ] do
    post :calculate, as: :calculate
  end

  resource :legacy_inss_calculator, only: [ :new, :show ] do
    post :calculate, as: :calculate
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calculator/inss.rb
module Calculator
  class Inss
    attr_accessor :salary
    attr_reader :contribution

    def initialize(salary: 0)
      @salary = salary
      @calculator ||= InssCalculator::DiscountPrevidenceCalculator.new(salary)
      @contribution = @calculator.contribution
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # Restrict the browsers only when a bug appears.
  # allow_browser versions: :modern
  around_action :sentry_exception

  protected

  def sentry_exception
    begin
      yield
    rescue StandardError => exception
      Sentry.capture_exception(exception)
      raise exception
    end
  end
end

app/controllers/inss_calculators_controller.rb
class InssCalculatorsController < ApplicationController
  before_action :inss_calculator

  def new
  end

  def show
    @inss_calculator
  end

  def calculate
    redirect_to action: :show, public: salary_params[:public], salary: salary_params[:salary]
  end

  private

  def salary_params
    params.permit(:salary, :public)
  end

  def inss_calculator
    @inss_calculator = calculator
  end

  def calculator
    @calculator = if salary_params[:public].to_i.zero?
      InssCalculator::DiscountPrevidenceCalculator.new(salary_params[:salary])
    else
      InssCalculator::PublicInssCalculator.new(salary_params[:salary])
    end

   InssCalculator::Decorator::Text.new(@calculator)
  end
end

app/controllers/legacy_inss_calculators_controller.rb
class LegacyInssCalculatorsController < ApplicationController
  before_action :inss_calculator

  def new
  end

  def show
    @inss_calculator
  end

  def calculate
    redirect_to action: :show, public: salary_params[:public], salary: salary_params[:salary]
  end

  private

  def salary_params
    params.permit(:salary, :public)
  end

  def inss_calculator
    @inss_calculator = calculator
  end

  def calculator
    @calculator = if salary_params[:public].to_i.zero?
      InssCalculator::Legacy::DiscountPrevidenceCalculator.new(salary_params[:salary])
    else
      InssCalculator::Legacy::PublicInssCalculator.new(salary_params[:salary])
    end

   InssCalculator::Decorator::Text.new(@calculator)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inss_calculators_helper.rb
module InssCalculatorsHelper
  def legacy_inss_law_link(text = nil)
    base_url =  "https://www.in.gov.br/en/web/dou/-/portaria-interministerial-mps/mf-n-2-de-11-de-janeiro-de-2024-537035232"
    text = text || "Portaria Interministerial n. 2 de 11 de Janeiro de 2024"
    link_to text, base_url, target: "_blank"
  end

  def inss_law_link(text = nil)
    base_url =  "https://www.in.gov.br/en/web/dou/-/portaria-interministerial-mps/mf-n-6-de-10-de-janeiro-de-2025-606526848"
    text = text || "Portaria Interministerial n. 6 de 10 de Janeiro de 2025"
    link_to text, base_url, target: "_blank"
  end
end

app/views/inss_calculators/_blog.html.erb
<div class="container mt-3 blog">
  <h1>Cálculo da contribuição do INSS 2025</h1>

  <p>
    A <%= inss_law_link %> determina como se dá o cálculo da contribuição do INSS. O cálculo é progressivo.
    Isto significa que ele foi pensado para taxar com alíquota menor quem recebe menos e taxar com alíquota maior na medida em que os salários escalam faixas salariais mais altas.
  </p>

  <p>
    A tabela com as faixas salariais está no <%= inss_law_link "Anexo II da referida Portaria Interna" %>.
  </p>

  <table class="table">
    <tbody>
      <tr>
        <td>Salário de contribuição (R$)</td>
        <td>Alíquota (%)</td>
      </tr>
      <tr>
        <td>Até 1.518,00</td>
        <td>7,5</td>
      </tr>
      <tr>
        <td>De 1.518,01 a 2.793,88</td>
        <td>9</td>
      </tr>
      <tr>
        <td>De 2.793,89 a 4.190,83</td>
        <td>12</td>
      </tr>
      <tr>
        <td>De 4.190,84 a 8.157,41</td>
        <td>14</td>
      </tr>
    </tbody>
  </table>

  <p>
    O salário mínimo de <em>R$ 1.518,00</em> em 2025, por exemplo, está na primeira faixa.
    Você deve usar a alíquota de 7,5%. A contribuição para este salário é de R$ 113,85. Já o salário de R$ 2.793,88 está  na segunda faixa salarial.
    Você deve aplicar a alíquota da primeira faixa até o limite de R$ 1.518,00 e, após isto, aplicar a alíquota da segunda faixa sobre o montante restante.
    Aqui você deve ter muita atenção. A alíquota da segunda faixa vai ser aplicada somente à diferença entre o salário de contribuição e o limite da faixa anterior.
  </p>

  <p>
    Pense nas diferentes alíquotas sendo aplicadas em diferentes partes do salário da seguinte forma.
    Vamos chamar de Kg de sal ao invés de dinheiro por um momento.

    Você chegou ao INSS com uma quantidade de sal. Pesados, a balança apontou seus 2.793,88 Kg de sal.
    A primeira parte vai ser separada para a balança da primeira faixa salarial.
    Você retira do seu montante uma parte até a balança marcar 1.518,00 Kg.
    O INSS vai recolher 7,5% desse montante, ou seja, 113,85 Kg. Desta primeira balança, vai restar para você 1.275,88 Kg.
    Guarde este valor. Deixemos este resto em espera e vamos olhar para a segunda parte do seu salário.
    Lembre-se que você separou 1.518,00 Kg para ser medido na primeira balança.
    Agora você deposita sobre a segunda balança o que tem consigo e o resultado é 2.793,88 Kg menos os 1.518,00 Kg que já foi medido na primeira balança.
  </p>

  <p>
    Sobre a segunda balança, portanto, tem-se 1.275,88 Kg. Esta segunda balança sofre uma taxa de 9% sobre os 1.275,88 Kg.
    Note que esta segunda etapa tem uma taxação maior do que a anterior.
    O INSS, deveria recolher 114,8292 Kg fruto desta taxa de 9%.
    Mas vai considerar somente as duas primeiras casas decimais após a vírgula. Vai recolher 114,82 Kg.
    Desta segunda rodada sobra para você 1.161,06 Kg. Da primeira rodada restou para você 1.404,15 Kg.
    A soma dos dois montantes é o seu salário líquido.
    Obviamente estamos falando de salário em dinheiro até porque quem consegue carregar sozinho mais de 2 mil quilos de sal?
    Seu salário líquido é de R$ 2.565,21 (a soma de 1.404,15 e 1.161,06).

    Embora saibamos que o INSS recolheu para si R$ 228,67, este montante não foi fruto de uma única taxa fixa.
  </p>

  <h3>Como se calcula para as demais faixas salariais?</h3>

  <p>
    No exemplo com as balanças, estas representam a quantidade de rodadas pelas quais um salário 
    será distribuido para ser taxado sob diferentes alíquotas. Para um salário que esteja dentro da terceira faixa salarial,
    digamos, R$ 3.000,00, acrescenta-se a terceira balança de alíquota 12% sobre a diferença entre 3.000,00 e 2.793,89.
    Ou seja, 12% de R$ 206,11, que é R$ 24,73. Por fim, soma-se este montante com os demais fruto do resultado das porcentagens da primeira
    e da segunda rodada de taxação das duas primeiras balanças.
  </p>

  <p>Atenção, salários muito acima do limite da última faixa salarial são taxados até o limite de R$ 951,62
  para o regime CLT. Ou seja, aplicado todas as rodadas de taxação sobre um salário muito alto, o INSS não pode recolher
  mais do que R$ 951,62.</p>

  <h3>Como funciona o cálculo para o servidor público?</h3>

  <p>A explicação sobre o cálculo do regime CLT permanece válida. Vamos destacar aqui somente as
  diferenças.</p>

  <p>Existem mais faixas salariais no cálculo para o servidor público. A tabela do servidor público 
    está no <%= inss_law_link "Anexo III da referida Portaria Interministerial de 2025" %>.
  </p>

  <table class="table">
    <tbody>
      <tr>
        <td>Salário de contribuição (R$)</td>
        <td>Alíquota (%)</td>
      </tr>
      <tr>
        <td>Até 1.518,00</td>
        <td>7,5</td>
      </tr>
      <tr>
        <td>De 1.518,01 a 2.793,88</td>
        <td>9</td>
      </tr>
      <tr>
        <td>De 2.793,89 a 4.190,83</td>
        <td>12</td>
      </tr>
      <tr>
        <td>De 4.190,84 a 8.157,41</td>
        <td>14</td>
      </tr>
      <tr>
        <td>De 8.157,42 a 13.969,49</td>
        <td>14,5</td>
      </tr>
      <tr>
        <td>De 13.969,50 a 27.938,95</td>
        <td>16,5</td>
      </tr>
      <tr>
        <td>De 27.938,96 a 54.480,97</td>
        <td>19</td>
      </tr>
      <tr>
        <td>Acima de 54.480,97</td>
        <td>22</td>
      </tr>
    </tbody>
  </table>

  <p>Vamos olhar para a última faixa salarial. Os salários acima de 54.480,97 são taxados em 22%.
  Ou seja, sem limite sobre o montante que deve ser recolhido. Enquanto que no regime CLT, os salário acima 
  da última faixa salarial da tabela CLT não podem ser taxados acima do limite de R$ 908,85.</p>

  <h3>O que é o salário de contribuição?</h3>

  <p>
    O salário de contribuição que aparece no contra-cheque é a soma do salário base mais as eventuais horas extras.
    Fica de fora do salário de contribuição o descanso remunerado, auxílio família, vale transporte, vale alimentação.
    É sobre este salário de contribuição que se calcula a contribuição do INSS.
  </p>

  <h3>As horas extras entram no cálculo do salário de contribuição?</h3>

  <p>
    Sim. O salário de contribuição envolve os ganhos mediante o tempo de trabalho.
  </p>

  <h3>Como fica o cálculo com o novo salário mínimo de 2025?</h3>

  <p>
    O novo salário mínimo é de <%= link_to "R$ 1.518,00", "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/decreto/D12342.htm", target: "_blank" %>.
    O Ministério da Previdência Social divulgou a nova <%= link_to "tabela para 2025", "https://www.gov.br/secom/pt-br/assuntos/noticias/2025/janeiro/inss-divulga-os-novos-valores-dos-beneficios-para-2025", target: "_blank" %>.
  </p>

  <p>
    O princípio de taxar salários maiores com taxas maiores e salários menores com taxas menores permanece.
    Isto significa que o princípio da progressividade continua.
  </p>

  <h3>E a calculadora de 2024?</h3>

  <p>Se você ainda precisa calcular a contribuição do ano de 2024, vá para a <%= link_to "Calculadora 2024", new_legacy_inss_calculator_path, data: { turbo: false } %>.</p>
</div>

app/views/inss_calculators/index.html.erb
<main class="container" %>
  <div class="card shadow">
    <div class="card-body">
      <div class="card-header mb-3">
        <h1>
          Calcule sua contribuição do INSS
        </h1>
        <p class="form-text">Você deve informar seu salário bruto também conhecido como salário de contribuição.
        Considere a soma de todos os seus benefícios, adicional da família, horas extras, vale transporte etc.</p>
      </div>

      <%= form_with url: inss_calculators_calculate_path, method: :post, class: "row row-cols-lg-auto g-3 align-items-center" do |form| %>
      <div class="col-12">
        <div class="input-group">
          <div class="input-group-text">
            R$
          </div>
          <%= form.number_field :salary, step: 0.01, class: "form-control" %>
        </div>
      </div>
      <div class="col-12">
        <div class="d-grid gap-2">
          <%= form.submit "Calcular", class: "btn btn-lg btn-primary" %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</main>

app/views/inss_calculators/new.html.erb
<%= javascript_include_tag 'TheMask', 'data-turbo-track': 'reload', defer: true %>
<%= javascript_include_tag 'inssCalculatorView', 'data-turbo-track': 'reload', defer: true %>

<div class="main">
  <!-- Masthead-->
  <div class="masthead">
    <div class="masthead-content text-white">
      <div class="container-fluid px-4 px-lg-0">
        <h1 class="fst-italic lh-1 mb-4">Calcule sua contribuição do INSS 2025</h1>
        <p class="mb-5">Você deve informar seu salário bruto também conhecido como <em>Salário de contribuição</em>.
          Some o <em>Salário Base</em>, as <em>Horas Extras</em> e o <em>Repouso Remunerado</em>.
        </p>
        <%= form_with url: calculate_inss_calculator_path, method: :post, id: "inss_calculator_form" do |form| %>
          <div id="input-group-calculator" class="row input-group-newsletter mb-4">
            <div class="col">
              <%= form.text_field :masked_salary, class: "form-control", value: "1.518,00", placeholder: "Somente números" %>
              <%= form.hidden_field :salary %>
            </div>
            <div class="col-auto">
              <%= form.submit "Calcular", id: "insss_calculator_submit_button", class: "btn btn-primary", data: { turbo: false } %>
            </div>
            <div id="input-salary-alert">
            </div>
          </div>
          <div>
            <div class="form-check">
              <%= form.check_box :public, class: "form-check-input", value: "false" %>
              <%= form.label :public, "Servidor Público", class: "form-check-label" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "icons" %>
</div>

<%= render "layouts/ads" %>

<%= render "blog" %>

app/views/layouts/_ads.html.erb
<div>
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=<%= ENV['ADSENSE_CLIENT_ID'] %>"
      crossorigin="anonymous"></script>
  <!-- Placa do bloco principal -->
  <ins class="adsbygoogle"
      style="display:block"
      data-ad-client="<%= ENV['ADSENSE_CLIENT_ID'] %>"
      data-ad-slot="<%= ENV['ADSENSE_AD_SLOT'] %>"
      data-ad-format="auto"
      data-full-width-responsive="true"></ins>
  <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="containter">
    <!-- Social Icons-->
    <!-- For more icon options, visit https://fontawesome.com/icons?d=gallery&p=2&s=brands-->
    <div class="footer-social-icons row m-0">
      <div class="col-6 d-flex justify-content-center align-items-center">
        <a class="text-white" href="/">Calcula INSS</a>
      </div>
      <div class="col-6">
        <div class="d-flex flex-row justify-content-end mt-0">
          <a class="btn btn-dark m-3" href="https://github.com/Pauloparakleto/daskapital"><i class="fab fa-github fa-sm"></i></a>
          <a class="btn btn-dark m-3" href="https://www.linkedin.com/in/paulo-souza-a8998410a/"><i class="fab fa-linkedin fa-sm"></i></a>
          <a class="btn btn-dark m-3" href="https://www.youtube.com/@paulofelipesilvadesouza7287"><i class="fab fa-youtube fa-sm"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Calcula INSS" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= Sentry.get_trace_propagation_meta.html_safe %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/legacy_inss_calculators/_blog.html.erb
<div class="container mt-3 blog">
  <h1>Cálculo da contribuição do INSS 2024</h1>

  <p><em>Você pode navegar para a nova <%= link_to "calculadora 2025", new_inss_calculator_path, data: { turbo: false }%>.</em></p>

  <p>
    A <%= legacy_inss_law_link %> determina como se dá o cálculo da contribuição do INSS. O cálculo é progressivo.
    Isto significa que ele foi pensado para taxar com alíquota menor quem recebe menos e taxar com alíquota maior na medida em que os salários escalam faixas salariais mais altas.
  </p>

  <p>
   A tabela com as faixas salariais está no <%= legacy_inss_law_link "Anexo II da referida Portaria Interna" %>.
  </p>

  <table class="table">
    <tbody>
      <tr>
        <td>Salário de contribuição (R$)</td>
        <td>Alíquota (%)</td>
      </tr>
      <tr>
        <td>Até 1.412,00</td>
        <td>7,5</td>
      </tr>
      <tr>
        <td>De 1.412,01 a 2.666,68</td>
        <td>9</td>
      </tr>
      <tr>
        <td>De 2.666,69 a 4.000,03</td>
        <td>12</td>
      </tr>
      <tr>
        <td>De 4.000,04 a 7.786,02</td>
        <td>14</td>
      </tr>
    </tbody>
  </table>

  <p>
    O salário mínimo de <em>R$ 1.412,00</em> em 2024, por exemplo, está na primeira faixa. 
    Você deve usar a alíquota de 7,5%. A contribuição para este salário é de R$ 105,90. Já o salário de R$ 2.666,68 está  na segunda faixa salarial. Você deve aplicar a alíquota da primeira faixa até o limite de R$ 1.412,00 e, após isto, aplicar a alíquota da segunda faixa sobre o montante restante. Aqui você deve ter muita atenção. A alíquota da segunda faixa vai ser aplicada somente à diferença entre o salário de contribuição e o limite da faixa anterior.
  </p>

  <p>
    Pense nas diferentes alíquotas sendo aplicadas em diferentes partes do salário da seguinte forma.
    Vamos chamar de Kg de sal ao invés de dinheiro por um momento.

    Você chegou ao INSS com uma quantidade de sal. Pesados, a balança apontou seus 2.666.68 Kg de sal.
    A primeira parte vai ser separada para a balança da primeira faixa salarial.
    Você retira do seu montante uma parte até a balança marcar 1.412,00 Kg.
    O INSS vai recolher 7,5% desse montante, ou seja, 105,90 Kg. Desta primeira balança, vai restar para você 1.306,10 Kg. 
    Guarde este valor. Deixemos este resto em espera e vamos olhar para a segunda parte do seu salário. 
    Lembre-se que você separou 1.412,00 Kg para ser medido na primeira balança.
    Agora você deposita sobre a segunda balança o que tem consigo e o resultado é 2.666,68 Kg menos os 1.412,00 Kg que já foi medido na primeira balança.
  </p>

  <p>
    Sobre a segunda balança, portanto, tem-se 1.254,68 Kg. Esta segunda balança sofre uma taxa de 9% sobre os 1.254,68 Kg.
    Note que esta segunda etapa tem uma taxação maior do que a anterior.
    O INSS, deveria recolher 112,9212 Kg fruto desta taxa de 9%.
    Mas vai considerar somente as duas primeiras casas decimais após a vírgula. Vai recolher, então, 112,92 Kg.
    Desta segunda rodada sobra para você 1.141,76 Kg.

    Da primeira rodada restou para você 1.306,10 Kg e da segunda rodada sobrou 1.141,76 Kg. 
    A soma dos dois montantes é o seu salário líquido.
    Obviamente estamos falando de salário em dinheiro até porque quem consegue carregar sozinho mais de 2 mil quilos de sal?
    Seu salário líquido é de R$ 2.447,86 (a soma de 1.306,10 e 1.141,76).

    Embora saibamos que o INSS recolheu para si R$ 218,82, este montante não foi fruto de uma única taxa fixa.
  </p>

  <h3>Como se calcula para as demais faixas salariais?</h3>

  <p>
    No exemplo com as balanças, estas representam a quantidade de rodadas pelas quais um salário 
    será distribuido para ser taxado sob diferentes alíquotas. Para um salário que esteja dentro da terceira faixa salarial, 
    digamos, R$ 3.000,00, acrescenta-se a terceira balança de alíquota 12% sobre a diferença entre 3.000,00 e 2.666,69.
    Ou seja, 12% de R$ 333,31,  que é R$ 39,9972. Novamente, considera-se somente as duas primeiras casas decimais após 
    a vírgula, R$ 39,99. Por fim, soma-se este montante com os demais fruto do resultado das porcentagens da primeira
    e da segunda rodada de taxação das duas primeiras balanças.
  </p>

  <p>Atenção, salários muito acima do limite da última faixa salarial são taxados até o limite de R$ 908,85
  para o regime CLT. Ou seja, aplicado todas as rodadas de taxação sobre um salário muito alto, o INSS não pode recolher
  mais do que R$ 908,85.</p>

  <h3>Como funciona o cálculo para o servidor público?</h3>

  <p>A explicação sobre o cálculo do regime CLT permanece válida. Vamos destacar aqui somente as
  diferenças.</p>

  <p>Existem mais faixas salariais no cálculo para o servidor público. A tabela do servidor público 
    está no <%= legacy_inss_law_link "Anexo III da referida Portaria Interna" %>.
  </p>

  <table class="table">
    <tbody>
      <tr>
        <td>Salário de contribuição (R$)</td>
        <td>Alíquota (%)</td>
      </tr>
      <tr>
        <td>Até 1.412,00</td>
        <td>7,5</td>
      </tr>
      <tr>
        <td>De 1.412,01 a 2.666,68</td>
        <td>9</td>
      </tr>
      <tr>
        <td>De 2.666,69 a 4.000,03</td>
        <td>12</td>
      </tr>
      <tr>
        <td>De 4.000,04 a 7.786,02</td>
        <td>14</td>
      </tr>
      <tr>
        <td>De 7.786,03 a 13.333,48</td>
        <td>14,5</td>
      </tr>
      <tr>
        <td>De 13.333,49 a 26.666,94</td>
        <td>16,5</td>
      </tr>
      <tr>
        <td>De 26.666,94 a 52.000,54</td>
        <td>19</td>
      </tr>
      <tr>
        <td>Acima de 52.000,54</td>
        <td>22</td>
      </tr>
    </tbody>
  </table>

  <p>Vamos olhar para a última faixa salarial. Os salários acima de 52.000,54 são taxados em 22%.
  Ou seja, sem limite sobre o montante que deve ser recolhido. Enquanto que no regime CLT, os salário acima 
  da última faixa salarial da tabela CLT não podem ser taxados acima do limite de R$ 908,85.</p>

  <h3>O que é o salário de contribuição?</h3>

  <p>
    O salário de contribuição que aparece no contra-cheque é a soma do salário base mais as eventuais horas extras.
    Fica de fora do salário de contribuição o descanso remunerado, auxílio família, vale transporte, vale alimentação.
    É sobre este salário de contribuição que se calcula a contribuição do INSS.
  </p>

  <h3>As horas extras entram no cálculo do salário de contribuição?</h3>

  <p>
    Sim. O salário de contribuição envolve os ganhos mediante o tempo de trabalho.
  </p>

  <h3>Como fica o cálculo com o novo salário mínimo de 2025?</h3>

  <p>
    O novo salário mínimo é de <%= link_to "R$ 1.518,00", "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/decreto/D12342.htm", target: "_blank" %>. 
    O Ministério da Previdência Social divulgou a nova <%= link_to "tabela para 2025", "https://www.gov.br/secom/pt-br/assuntos/noticias/2025/janeiro/inss-divulga-os-novos-valores-dos-beneficios-para-2025", target: "_blank" %>.
  </p>

  <p>
    O princípio de taxar salários maiores com taxas maiores e salários menores com taxas menores permanece.
    Isto significa que o princípio da progressividade continua.
  </p>

  <p>Você pode navegar para a nova <%= link_to "calculadora 2025", new_inss_calculator_path %>.</p>
</div>

app/views/legacy_inss_calculators/_icons.html.erb
<!-- Social Icons-->
<!-- For more icon options, visit https://fontawesome.com/icons?d=gallery&p=2&s=brands-->
<div class="social-icons">
    <div class="d-flex flex-row flex-lg-column justify-content-center align-items-center h-100 mt-3 mt-lg-0">
        <a class="btn btn-dark m-3" href="https://github.com/Pauloparakleto/daskapital"><i class="fab fa-github fa-2xl"></i></a>
        <a class="btn btn-dark m-3" href="https://www.linkedin.com/in/paulo-souza-a8998410a/"><i class="fab fa-linkedin fa-2xl"></i></a>
        <a class="btn btn-dark m-3" href="https://www.youtube.com/@paulofelipesilvadesouza7287"><i class="fab fa-youtube fa-2xl"></i></a>
    </div>
</div>

app/views/legacy_inss_calculators/new.html.erb
<%= javascript_include_tag 'TheMask', 'data-turbo-track': 'reload', defer: true %>
<%= javascript_include_tag 'inssCalculatorView', 'data-turbo-track': 'reload', defer: true %>

<div class="main">
  <!-- Masthead-->
  <div class="masthead">
    <div class="masthead-content text-white">
      <div class="container-fluid px-4 px-lg-0">
        <h1 class="fst-italic lh-1 mb-4">Calcule sua contribuição do INSS 2024</h1>
        <p class="mb-5">Você deve informar seu salário bruto também conhecido como <em>Salário de contribuição</em>.
          Some o <em>Salário Base</em>, as <em>Horas Extras</em> e o <em>Repouso Remunerado</em>.
        </p>
        <%= form_with url: calculate_legacy_inss_calculator_path, method: :post, id: "inss_calculator_form" do |form| %>
          <div id="input-group-calculator" class="row input-group-newsletter mb-4">
            <div class="col">
              <%= form.text_field :masked_salary, class: "form-control", value: "1412,00", placeholder: "Somente números" %>
              <%= form.hidden_field :salary %>
            </div>
            <div class="col-auto">
              <%= form.submit "Calcular", id: "insss_calculator_submit_button", class: "btn btn-primary", data: { turbo: false } %>
            </div>
            <div id="input-salary-alert">
            </div>
          </div>
          <div>
            <div class="form-check">
              <%= form.check_box :public, class: "form-check-input", value: "false" %>
              <%= form.label :public, "Servidor Público", class: "form-check-label" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <%= render "icons" %>
</div>

<%= render "blog" %>

app/views/legacy_inss_calculators/show.html.erb
<div class="main">
  <div class="masthead">
    <div class="masthead-content text-white">
      <div class="container-fluid px-4 px-lg-0">
        <h1 class="fst-italic lh-1 mb-4">Sua contribuição do INSS</h1>
        <h2><%= @inss_calculator.contribution %></h2>
          <p><%= @inss_calculator.present %></p>
        <%= link_to "Realizar outro cálculo", new_legacy_inss_calculator_path, class: "btn btn-primary btn-lg", data: { turbo: false }%>
      </div>
    </div>
  </div>

  <%= render "icons" %>
</div>


<%= render "blog" %>